database:
  - name: "test"
    host: "localhost"
    port: 5432
    db: "users"
    password: "password"
    user: "postgres"
    schema: "public"
    driver: "postgres"
  - name: "prod"
    # example endpoint
    host: "mydb.123456789012.us-east-1.rds.amazonaws.com"
    port: 5432
    db: "users"
    password: "password"
    user: "postgres"
    schema: "public"
    driver: "postgres"
  - name: "oracle"
    host: "localhost"
    port: 1521
    db: "FREEPDB1 "
    password: "password"
    user: "system"
    driver: "oracle"
    ssl: "enable"
    wallet: "path/to/wallet"
    ssl-verify: true
    trace: "trace.log"
  - name: "sqlserver"
    driver: "sqlserver"
    host: "localhost"
    port: 1433
    db: "msdb"
    password: "5@klkbN#ABC"
    user: "SA"
limit: 50
keybindings:
  run-query: 'Ctrl-Space'
  structure: 'Ctrl-S'
  indexes: 'Ctrl-I'
  constraints: 'Ctrl-T'
  clear-editor: 'Ctrl-D'
  navigation:
    up: 'Ctrl-K'
    down: 'Ctrl-J'
    left: 'Ctrl-H'
    right: 'Ctrl-L'
