# Options for analysis running.
run:
  timeout: 5m
  skip-dirs:
    - .git
linters:
   enable:
    - revive
    - godot
    - gofmt
linters-settings:
  revive:
    rules:
      - name: blank-imports
        severity: warning
        disabled: true
