before:
  hooks:
    - go mod tidy
builds:
  - id: "main"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  mode: append
  extra_files:
    - glob: ./dblab-build/**/*
    - glob: ./dblab-build/checksums.txt
  name_template: "Release {{.Tag}}"

brews:
    # Name template of the recipe
  - name: dblab

    # GitHub/GitLab repository to push the formula to
    tap:
      owner: danvergara
      name: homebrew-tools

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: danvergara
      email: daniel.omar.vergara@gmail.com

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/danvergara/dblab"

    # Your app's description.
    # Default is empty.
    description: "Interactive client for PostgreSQL and MySQL"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "MIT"
