before:
  hooks:
    - go mod tidy
builds:
  - id: darwin-sqlite
    binary: dblab-sqlite
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{ .ProjectName }}_sqlite_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
snapshot:
  name_template: "{{ .Tag }}-next"
