before:
  hooks:
    - go mod tidy
builds:
  - id: windows-sqlite
    binary: dblab-sqlite
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - amd64
archives:
  - name_template: "{{ .ProjectName }}_sqlite_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
snapshot:
  name_template: "{{ .Tag }}-next"
