before:
  hooks:
    - go mod tidy
builds:
  - id: linux-sqlite
    binary: dblab-sqlite
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: linux
        goarch: amd64
        env:
          - CC=gcc
snapshot:
  name_template: "{{ .Tag }}-next"
