services:
  ssh:
    image: rastasheep/ubuntu-sshd:latest
    container_name: test-ssh
    ports:
      - "2222:22"
    environment:
      - ROOT_PASSWORD=root
    networks:
      - private-network
      - public-network

  postgres:
    image: postgres:15
    container_name: test-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    networks:
      - private-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 5@klkbN#ABC
      MYSQL_ROOT_PASSWORD: myuser
      MYSQL_DATABASE: mydb
    networks:
      - private-network

  dblab:
    build:
      context: .
      target: builder
    volumes:
      - ./:/src/app:z
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=users
      - DB_PORT=5432
      - DB_DRIVER=postgres
      - DB_SCHEMA=public
    entrypoint: ["/bin/bash", "./scripts/entrypoint.dev.sh"]
    networks:
      - private-network

  dblab-mysql:
    build:
      context: .
      target: builder
    volumes:
      - ./:/src/app:z
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=myuser
      - DB_PASSWORD=5@klkbN#ABC
      - DB_NAME=mydb
      - DB_PORT=3306
      - DB_DRIVER=mysql
    entrypoint: ["/bin/bash", "./scripts/entrypoint-mysql.dev.sh"]
    networks:
      - private-network

networks:
  private-network:
    internal: true  # Makes this network inaccessible from outside Docker
  public-network:
