version: "3.9"

services:
  postgres:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    ports:
      - '5432:5432'
    networks:
      - dblab
  
  dblab:
    build:
      context: .
      target: builder
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=users
      - DB_PORT=5432
      - DB_DRIVER=postgres
    entrypoint: ["/bin/bash", "./scripts/entrypoint.dev.sh"]
    networks:
      - dblab

networks:
  dblab:
