services:
  ssh:
    image: rastasheep/ubuntu-sshd:latest
    container_name: test-ssh
    ports:
      - "2222:22"
    environment:
      - ROOT_PASSWORD=root
    networks:
      - private-network
      - public-network

  postgres:
    image: danvergara/sakila:postgres-18.4
    container_name: test-postgres
    networks:
      - private-network

  mysql:
    image: danvergara/sakila:mysql-8.4
    networks:
      - private-network

networks:
  private-network:
    internal: true  # Makes this network inaccessible from outside Docker
  public-network:
