services:
  postgres:
    image: danvergara/sakila:postgres-18.4
    ports:
      - '5432:5432'
    networks:
      - dblab

  mysql:
    image: danvergara/sakila:mysql-8.4
    ports:
      - '3306:3306'
    networks:
      - dblab

  oracle:
    image: container-registry.oracle.com/database/free:latest
    environment:
      ORACLE_PWD: password
    ports:
      - '1521:1521'
    networks:
      - dblab

  mssql:
    image: danvergara/sakila:mssql-2025
    environment:
      MSSQL_SA_PASSWORD: 5@klkbN#ABC
      ACCEPT_EULA: Y
    ports:
      - '1433:1433'
    networks:
      - dblab

networks:
  dblab:
