services:
  ssh:
    image: rastasheep/ubuntu-sshd:latest
    container_name: test-ssh
    ports:
      - "2222:22"
    environment:
      - ROOT_PASSWORD=root
    networks:
      - private-network
      - public-network

  postgres:
    image: danvergara/sakila:postgres-18.4
    container_name: test-postgres
    networks:
      - private-network

  mysql:
    image: danvergara/sakila:mysql-8.4
    environment:
    networks:
      - private-network

  dblab:
    build:
      context: .
      target: builder
    volumes:
      - ./:/src/app:z
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=sakila
      - DB_PASSWORD=sakila
      - DB_NAME=sakila
      - DB_PORT=5432
      - DB_DRIVER=postgres
      - DB_SCHEMA=public
    networks:
      - private-network

  dblab-mysql:
    build:
      context: .
      target: builder
    volumes:
      - ./:/src/app:z
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=sakila
      - DB_PASSWORD=sakila
      - DB_NAME=sakila
      - DB_PORT=3306
      - DB_DRIVER=mysql
    networks:
      - private-network

networks:
  private-network:
    internal: true  # Makes this network inaccessible from outside Docker
  public-network:
